##Case Study - Types of Perceptron models for Deep Learning using AND gate and OR gate.


In [ ]:
from sklearn.linear_model import Perceptron

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1,1],[-1,1],[1,-1],[-1,-1]])

In [ ]:
t = np.array([[1],[-1],[-1],[-1]])

In [ ]:
per = Perceptron()

In [ ]:
w = per.fit(x,t)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
w.score(x,t)

1.0

In [ ]:
print(w.coef_)

[[1. 1.]]


In [ ]:
print(w.intercept_)

[-1.]


In [ ]:
print(w.predict(np.array([[1,1],[-1,1]])))

[ 1 -1]


In [ ]:
print(w.predict(np.array([[3,-2]])))

[-1]


####Example using AND gate

In [ ]:
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
t = np.array([[0], [0], [0], [1]])

In [ ]:
per = Perceptron()

In [ ]:
w = per.fit(x,t)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
w.score(x,t)

1.0

In [ ]:
print(w.predict(np.array([[0,0],[1,0]])))

[0 0]


In [ ]:
input = np.array([[1,-2,0,-1],[0,1.5,-0.5,-1],[-1,1,0.5,-1]])

In [ ]:
target = np.array([[-1],[-1],[1]])

In [ ]:
per1 = Perceptron()

In [ ]:
b = per1.fit(input,target)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
b.score(input,target)

1.0

In [ ]:
print(w.coef_,w.intercept_)

[[2. 2.]] [-2.]


In [ ]:
print(b.predict(np.array([[1,-2,0,-1],[0,1.5,-0.5,-1],[-1,1,0.5,-1]])))

[-1 -1  1]


In [ ]:
per1 = Perceptron(eta0=0.1)

In [ ]:
w1 = per1.fit(input,target,sample_weight=np.array([1,-1,0]))

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(w1.coef_, w1.intercept_)

[[ 0.   0.9 -0.3 -0.6]] [0.6]


In [ ]:
print(w1.max_iter)

1000
